name: python-autotests-basic # Имя проекта
channels:
  - conda-forge # conda-forge
dependencies:
  - python=3.13.14 # Python
  - requests # requests
  - selenium # Selenium
  - webdriver-manager # Webdriver
  - python-chromedriver-binary # Chromedriver-binary
  - pytest # pytest